#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
roi_diffusion_analyzer_v2.py

This script analyzes the diffusion properties of trajectories inside and outside ROIs.

Input:
- ROI-assigned trajectory data (.pkl file) generated by roi_loader_improved.py

Output:
- Summary statistics for diffusion coefficients inside and outside ROIs
- Histogram of diffusion coefficients inside and outside ROIs
- CDF plot of diffusion coefficients inside and outside ROIs
- Distribution comparison plot of diffusion coefficients inside and outside ROIs
- Box plot comparing diffusion coefficients inside and outside ROIs

Usage:
python roi_diffusion_analyzer_v2.py
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import pickle
from pathlib import Path
from datetime import datetime

# Global parameters
# =====================================
# Bin size for diffusion coefficient histogram (in µm^2/s) 
D_BIN_SIZE = 0.05
# Output directory name format
OUTPUT_DIR_FORMAT = 'roi_diffusion_analysis_%Y%m%d_%H%M%S'
# =====================================

def load_roi_data(file_path):
    """
    Load ROI-assigned trajectory data from pickle file.
    
    Args:
        file_path: Path to the pickle file
        
    Returns:
        Dictionary containing the ROI-assigned trajectory data
    """
    try:
        with open(file_path, 'rb') as f:
            data = pickle.load(f)
        print(f"Successfully loaded data from {file_path}")
        return data
    except Exception as e:
        print(f"Error loading data from {file_path}: {e}")
        return None

def analyze_diffusion(roi_data):
    """
    Analyze diffusion properties of trajectories inside and outside ROIs.
    
    Args:
        roi_data: Dictionary containing ROI-assigned trajectory data
        
    Returns:
        Tuple of (inside_D, outside_D) where:
        - inside_D: Array of diffusion coefficients for trajectories inside ROIs
        - outside_D: Array of diffusion coefficients for trajectories outside ROIs
    """
    inside_D = []
    outside_D = []
    
    for roi_id, trajectories in roi_data['roi_trajectories'].items():
        if roi_id == 'unassigned':
            # Trajectories outside ROIs
            for traj in trajectories:
                if 'D' in traj and not np.isnan(traj['D']):
                    outside_D.append(traj['D'])
        else:
            # Trajectories inside ROIs  
            for traj in trajectories:
                if 'D' in traj and not np.isnan(traj['D']):
                    inside_D.append(traj['D'])
    
    return np.array(inside_D), np.array(outside_D)

def plot_diffusion_histogram(inside_D, outside_D, output_path):
    """
    Plot histogram of diffusion coefficients inside and outside ROIs.
    
    Args:
        inside_D: Array of diffusion coefficients for trajectories inside ROIs
        outside_D: Array of diffusion coefficients for trajectories outside ROIs  
        output_path: Path to save the histogram plot
    """
    fig, ax = plt.subplots(figsize=(8, 6))
    
    # Plot histogram for trajectories inside ROIs
    ax.hist(inside_D, bins=np.arange(0, np.max(inside_D), D_BIN_SIZE), alpha=0.7, label='Inside ROIs')
    
    # Plot histogram for trajectories outside ROIs
    ax.hist(outside_D, bins=np.arange(0, np.max(outside_D), D_BIN_SIZE), alpha=0.7, label='Outside ROIs')
    
    ax.set_xlabel('Diffusion Coefficient ($\mu m^2/s$)')
    ax.set_ylabel('Count')
    ax.set_title('Diffusion Coefficient Distribution')
    ax.legend()
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()
    
    print(f"Diffusion histogram saved to {output_path}")

def plot_diffusion_cdf(inside_D, outside_D, output_path):
    """
    Plot CDF of diffusion coefficients inside and outside ROIs.
    
    Args:
        inside_D: Array of diffusion coefficients for trajectories inside ROIs 
        outside_D: Array of diffusion coefficients for trajectories outside ROIs
        output_path: Path to save the CDF plot
    """
    fig, ax = plt.subplots(figsize=(8, 6))
    
    # Compute and plot CDF for trajectories inside ROIs
    inside_cdf = np.sort(inside_D)
    inside_yvals = np.arange(len(inside_cdf))/float(len(inside_cdf))
    ax.plot(inside_cdf, inside_yvals, label='Inside ROIs')
    
    # Compute and plot CDF for trajectories outside ROIs
    outside_cdf = np.sort(outside_D)
    outside_yvals = np.arange(len(outside_cdf))/float(len(outside_cdf))
    ax.plot(outside_cdf, outside_yvals, label='Outside ROIs')
    
    ax.set_xlabel('Diffusion Coefficient ($\mu m^2/s$)')
    ax.set_ylabel('Cumulative Probability')
    ax.set_title('Diffusion Coefficient CDF')
    ax.legend()
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300)
    plt.close()
    
    print(f"Diffusion CDF plot saved to {output_path}")

def plot_diffusion_distributions(inside_D, outside_D, output_path):
    """
    Plot distribution comparison of diffusion coefficients inside and outside ROIs.
    
    Args:
        inside_D: Array of diffusion coefficients for trajectories inside ROIs
        outside_D: Array of diffusion coefficients for trajectories outside ROIs
        output_path: Path to save the distribution comparison plot
    """  
    fig, ax = plt.subplots(figsize=(8, 6))
    
    bins = np.linspace(0, max(np.max(inside_D), np.max(outside_D)), 50)
    
    ax.hist(inside_D, bins=bins, alpha=0.5, density=True, label='Inside ROIs')
    ax.hist(outside_D, bins=bins, alpha=0.5, density=True, label='Outside ROIs')
    
    ax.set_xlabel('Diffusion Coefficient ($\mu m^2/s$)')  
    ax.set_ylabel('Density')
    ax.set_title('Diffusion Coefficient Distribution Comparison')
    ax.legend(loc='upper right')
    
    plt.tight_layout()
    plt.savefig(output_path, dpi=300) 
    plt.close()
    
    print(f"Diffusion distribution comparison plot saved to {output_path}")

def plot_diffusion_boxplot(inside_D, outside_D, output_path):
    """
    Plot box plot comparing diffusion coefficients inside and outside ROIs.
    
    Args:
        inside_D: Array of diffusion coefficients for trajectories inside ROIs
        outside_D: Array of diffusion coefficients for trajectories outside ROIs 
        output_path: Path to save the box plot
    """
    fig, ax = plt.subplots(figsize=(8, 6))
    
    ax.boxplot([inside_D, outside_D], labels=['Inside ROIs', 'Outside ROIs'])
    
    ax.set_ylabel('Diffusion Coefficient ($\mu m^2/s$)')
    ax.set_title('Diffusion Coefficient Box Plot')
    
    plt.tight_layout() 
    plt.savefig(output_path, dpi=300)
    plt.close()
    
    print(f"Diffusion box plot saved to {output_path}")

def print_diffusion_summary(inside_D, outside_D):
    """
    Print summary statistics for diffusion coefficients inside and outside ROIs.
    
    Args:
        inside_D: Array of diffusion coefficients for trajectories inside ROIs
        outside_D: Array of diffusion coefficients for trajectories outside ROIs  
    """
    print("\nDiffusion Summary")
    print("=================")
    
    print(f"Inside ROIs (n={len(inside_D)}):")
    print(f"  Mean: {np.mean(inside_D):.3f} µm^2/s")
    print(f"  Median: {np.median(inside_D):.3f} µm^2/s") 
    print(f"  Std: {np.std(inside_D):.3f} µm^2/s")
    print(f"  Min: {np.min(inside_D):.3f} µm^2/s")
    print(f"  Max: {np.max(inside_D):.3f} µm^2/s")
    
    print(f"\nOutside ROIs (n={len(outside_D)}):")  
    print(f"  Mean: {np.mean(outside_D):.3f} µm^2/s")
    print(f"  Median: {np.median(outside_D):.3f} µm^2/s")
    print(f"  Std: {np.std(outside_D):.3f} µm^2/s") 
    print(f"  Min: {np.min(outside_D):.3f} µm^2/s")
    print(f"  Max: {np.max(outside_D):.3f} µm^2/s")

def main():
    """
    Main function to analyze diffusion properties of trajectories inside and outside ROIs.
    """
    print("\nROI Diffusion Analyzer")
    print("======================")
    
    # Ask for input file
    roi_data_file = input("Enter path to ROI-assigned trajectory data file (.pkl): ")  
    roi_data = load_roi_data(roi_data_file)
    if roi_data is None:
        print("Failed to load ROI data. Exiting.") 
        return
    
    # Create output directory
    output_dir_name = datetime.now().strftime(OUTPUT_DIR_FORMAT)
    output_base_dir = os.path.dirname(roi_data_file)
    output_dir = os.path.join(output_base_dir, output_dir_name)
    os.makedirs(output_dir, exist_ok=True)
    
    # Analyze diffusion properties
    inside_D, outside_D = analyze_diffusion(roi_data)
    
    # Print summary statistics 
    print_diffusion_summary(inside_D, outside_D)
    
    # Plot histogram
    plot_diffusion_histogram(inside_D, outside_D, os.path.join(output_dir, 'diffusion_histogram.png'))
    
    # Plot CDF
    plot_diffusion_cdf(inside_D, outside_D, os.path.join(output_dir, 'diffusion_cdf.png'))
    
    # Plot distribution comparison  
    plot_diffusion_distributions(inside_D, outside_D, os.path.join(output_dir, 'diffusion_distributions.png'))
    
    # Plot box plot
    plot_diffusion_boxplot(inside_D, outside_D, os.path.join(output_dir, 'diffusion_boxplot.png'))
    
    print(f"\nAnalysis results saved to {output_dir}")

if __name__ == "__main__":
    main()